package karazin.scala.users.group.week6.homework

import scala.concurrent.Future

import karazin.scala.users.group.week5.homework.givens.{given, _}
import karazin.scala.users.group.week6.homework.givens.IntEncoder.toJsonString

/*
  Write test for all programs in karazin.scala.users.group.week4.homework.givens

  Make sure that the following cases are tested:
    • json string representation for integers works
    • json string representation for booleans works
    • json string representation for strings works
    • json string representation for lists for integers, booleans and strings works
    • json string representation for maps for integers, booleans and strings works
    • all instances for integers, booleans, strings and lists should be randomly generated by scalacheck 
      (that's a good time to uncover homework implementations from the previous semester)

  Review:
    • https://www.json.org/json-en.html
    • https://scalameta.org/munit/docs/tests.html
    • https://scalameta.org/munit/docs/assertions.html
    • https://scalameta.org/munit/docs/assertions.html#compileerrors
    • https://scalameta.org/munit/docs/integrations/scalacheck.html
    
  NB: Do not use sync, this homework does not belong async stuff
    
 */
class GivensSuite extends munit.FunSuite:

  test("Int even") {
    assertEquals(
      200.toJsonString(), "200"
    )
  }

  test("Int odd") {
    assertEquals(
      JsonStringEncoder[Int]
        .encode(117), "117"
    )
  }

  test("Int zero") {
    assertEquals(
      JsonStringEncoder[Int]
        .encode(0), "0"
    )
  }

  test("Int negative") {
    assertEquals(
      JsonStringEncoder[Int]
        .encode(-7), "-7"
    )
  }

  test("Bool false") {
    assertEquals(
      JsonStringEncoder[Boolean]
        .encode(false), "false"
    )
  }

  test("Bool JSON true") {
    assertEquals(
      JsonStringEncoder[Boolean]
        .encode(true), "true"
    )
  }

  test("String") {
    assertEquals(
      JsonStringEncoder[String]
        .encode("Lorem ipsum dolor"), "\"Lorem ipsum dolor\""
    )
  }

  test("String Empty") {
    assertEquals(
      JsonStringEncoder[String]
        .encode(""), "\"\""
    )
  }

  test("List String") {
    assertEquals(
      JsonStringEncoder[List[String]]
        .encode("Lorem" :: "ipsum" :: "dolor" :: Nil), "[\"Lorem\", \"ipsum\", \"dolor\"]"
    )
  }

  test("List Booleans") {
    assertEquals(
      JsonStringEncoder[List[Boolean]]
        .encode(true :: false :: true :: Nil), "[true, false, true]"
    )
  }

  test("List Integers") {
    assertEquals(
      JsonStringEncoder[List[Int]]
        .encode(90 :: -119 :: 0 :: Nil), "[90, -119, 0]"
    )
  }

  test("List Empty") {
    assertEquals(
      JsonStringEncoder[List[Int]]
        .encode(Nil), "[]"
    )
  }